# Generated by Django 3.2.7 on 2021-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('RENT', 'RENT')], max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='properties_uploads')),
                ('area', models.IntegerField()),
                ('unit', models.CharField(choices=[('MARLA', 'MARLA'), ('Kanal', 'Kanal')], max_length=2000)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Plots', 'Plots'), ('Houses', 'Houses'), ('Appartment', 'Appartment'), ('Commercial', 'Commercial')], max_length=2000)),
                ('location', models.CharField(choices=[('Lahore', 'Lahore'), ('Gujranwala', 'Gujranwala'), ('Faisalabad', 'Faisalabad')], max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('number', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
            ],
        ),
    ]
