# Generated by Django 3.2.7 on 2021-10-24 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertie',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='propertie',
            name='dealer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertie',
            name='description',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertie',
            name='full_location',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertie',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
