# Generated by Django 3.2.7 on 2021-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_auto_20211024_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
