# Generated by Django 3.2.8 on 2021-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer_Register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('current_phone_number', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('address_2', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=300)),
            ],
        ),
    ]
