# Generated by Django 3.2.8 on 2021-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_dealer_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer_register',
            name='eligible',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
