# Generated by Django 3.2.8 on 2021-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_dealer_register_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_register',
            name='eligible',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5),
        ),
    ]
