# Generated by Django 3.2.8 on 2021-10-27 14:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_alter_dealer_register_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer_register',
            name='id_of',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=300),
        ),
    ]
