# Generated by Django 3.2.7 on 2021-10-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_auto_20211027_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='posted_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
