# Generated by Django 3.2.7 on 2021-10-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_propertie_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
