# Generated by Django 3.2.7 on 2021-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_propertie_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertie',
            name='dealer',
        ),
        migrations.AlterField(
            model_name='propertie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
